### ISSUE TITLE
Issue Patching

### ISSUE THREAD

**Issue by HackerYijia** [Eagler-CE/repo#11]
loaded 1113 patch files from the repo
   patching files...
   ............ERROR: Could not apply 'patches' directory to: minecraft_src_patch.jar
java.io.IOException: Could not patch file "net/minecraft/entity/item/EntityXPOrb.java"!
    at net.lax1dude.eaglercraft.v1_8.buildtools.task.diff.ApplyPatchesToZip.applyPatches(ApplyPatchesToZip.java:111)
    at net.lax1dude.eaglercraft.v1_8.buildtools.task.init.DecompileMinecraft.decompileMinecraft(DecompileMinecraft.java:209)
    at net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI.runCompiler0(CompileLatestClientGUI.java:218)
    at net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI.runCompiler(CompileLatestClientGUI.java:138)
    at net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientFrame$2.run(CompileLatestClientFrame.java:325)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.github.difflib.patch.PatchFailedException: could not apply patch due to POSITION_OUT_OF_TARGET
    at com.github.difflib.patch.Patch.lambda$new$e23a5734$1(Patch.java:73)
    at com.github.difflib.patch.Patch.applyTo(Patch.java:63)
    at net.lax1dude.eaglercraft.v1_8.buildtools.task.diff.ApplyPatchesToZip.applyPatches(ApplyPatchesToZip.java:109)
    ... 5 more

Error: Error: could not decompile and patch 1.8.8.jar from "/home/runner/repo/mcp918/1.8.8.jar"!
net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI$CompileFailureException: Error: could not decompile and patch 1.8.8.jar from "/home/runner/repo/mcp918/1.8.8.jar"!
    at net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI.runCompiler0(CompileLatestClientGUI.java:219)
    at net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI.runCompiler(CompileLatestClientGUI.java:138)
    at net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientFrame$2.run(CompileLatestClientFrame.java:325)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by vukle** [comment]
used wrong jar, go into assets/indexes to find your jar.

**Comment by HackerYijia** [comment]
assets/indexes don't exist???

**Comment by HackerYijia** [comment]
I used the correct jar though? It is in assets/indexes.
