### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Mantas22XYT** [Eagler-CE/repo#7]
```
Loading files from 'minecraft_res.jar'...
Patching files in 'minecraft_res.jar'...
   loaded 1 patch files from the repo
   patching files...
   ...............................................
Patched 1 files
Restored 0 files
Replaced 0 files
Deleted 88 files


TeaVM JARs will be downloaded from repository: https://repo1.maven.org/maven2/

downloading: https://repo1.maven.org/maven2/org/teavm/teavm-core/0.6.1/teavm-core-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-cli/0.6.1/teavm-cli-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-tooling/0.6.1/teavm-tooling-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-platform/0.6.1/teavm-platform-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-classlib/0.6.1/teavm-classlib-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-interop/0.6.1/teavm-interop-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-jso/0.6.1/teavm-jso-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-jso-apis/0.6.1/teavm-jso-apis-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-jso-impl/0.6.1/teavm-jso-impl-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-metaprogramming-api/0.6.1/teavm-metaprogramming-api-0.6.1.jar
downloading: https://repo1.maven.org/maven2/org/teavm/teavm-metaprogramming-impl/0.6.1/teavm-metaprogramming-impl-0.6.1.jar
downloading: https://repo1.maven.org/maven2/joda-time/joda-time/2.7/joda-time-2.7.jar
downloading: https://repo1.maven.org/maven2/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar

Extracting decompiled source...
Scanning source folder paths...

"D:\eg\jdk\bin\javac.exe" -Xlint:-unchecked -Xlint:-options -Xlint:-deprecation -source 1.8 -target 1.8 -classpath "D:\eg\buildtools\##TEAVM.TMP##\joda-time-2.7.jar;D:\eg\buildtools\##TEAVM.TMP##\jzlib-1.1.3.jar;D:\eg\buildtools\##TEAVM.TMP##\teavm-classlib-0.6.1.jar;D:\eg\buildtools\##TEAVM.TMP##\teavm-interop-0.6.1.jar;D:\eg\buildtools\##TEAVM.TMP##\teavm-jso-0.6.1.jar;D:\eg\buildtools\##TEAVM.TMP##\teavm-jso-apis-0.6.1.jar;D:\eg\buildtools\##TEAVM.TMP##\teavm-jso-impl-0.6.1.jar;D:\eg\buildtools\##TEAVM.TMP##\teavm-metaprogramming-api-0.6.1.jar;D:\eg\buildtools\##TEAVM.TMP##\teavm-metaprogramming-impl-0.6.1.jar;D:\eg\buildtools\##TEAVM.TMP##\teavm-platform-0.6.1.jar" -sourcepath "D:\eg\out\build\MinecraftSrc\minecraft_src_javadoc.jar;D:\eg\sources\main\java;D:\eg\sources\teavm\java" -d "D:\eg\out\build\classes" "@D:\eg\out\build\sourceFiles.txt" 

Compiling 2042 source files...

D:\eg\sources\main\java\com\google\common\collect\ContiguousSet.java:171: error: unmappable character (0x88) for encoding windows-1257
	 * return {@code [1..�?�)}.
	                      ^D:\eg\sources\main\java\com\google\common\collect\Range.java:76: error: unmappable character (0x88) for encoding windows-1257
 * <td>{@code (a..+�?�)}
                    ^
D:\eg\sources\main\java\com\google\common\collect\Range.java:80: error: unmappable character (0x88) for encoding windows-1257
 * <td>{@code [a..+�?�)}
                    ^
D:\eg\sources\main\java\com\google\common\collect\Range.java:84: error: unmappable character (0x88) for encoding windows-1257
 * <td>{@code (-�?�..b)}
                 ^
D:\eg\sources\main\java\com\google\common\collect\Range.java:88: error: unmappable character (0x88) for encoding windows-1257
 * <td>{@code (-�?�..b]}
                 ^
D:\eg\sources\main\java\com\google\common\collect\Range.java:92: error: unmappable character (0x88) for encoding windows-1257
 * <td>{@code (-�?�..+�?�)}
                 ^
D:\eg\sources\main\java\com\google\common\collect\Range.java:92: error: unmappable character (0x88) for encoding windows-1257
 * <td>{@code (-�?�..+�?�)}
                       ^
D:\eg\sources\main\java\com\google\common\collect\Range.java:672: error: unmappable character (0x88) for encoding windows-1257
	 * <li>[start..+�?�)
	                 ^
D:\eg\sources\main\java\com\google\common\collect\Range.java:673: error: unmappable character (0x88) for encoding windows-1257
	 * <li>(-�?�..end) (only if type {@code C} is unbounded below)
	          ^
D:\eg\sources\main\java\com\google\common\collect\Range.java:674: error: unmappable character (0x88) for encoding windows-1257
	 * <li>(-�?�..+�?�) (only if type {@code C} is unbounded below)
	          ^
D:\eg\sources\main\java\com\google\common\collect\Range.java:674: error: unmappable character (0x88) for encoding windows-1257
	 * <li>(-�?�..+�?�) (only if type {@code C} is unbounded below)
	                ^
D:\eg\sources\main\java\com\google\common\collect\RangeSet.java:229: error: unmappable character (0xA5) for encoding windows-1257
	 * {@code " [1��?3](4��?+�?�)}"}.
	                ^
D:\eg\sources\main\java\com\google\common\collect\RangeSet.java:229: error: unmappable character (0xA5) for encoding windows-1257
	 * {@code " [1��?3](4��?+�?�)}"}.
	                       ^
D:\eg\sources\main\java\com\google\common\collect\RangeSet.java:229: error: unmappable character (0x88) for encoding windows-1257
	 * {@code " [1��?3](4��?+�?�)}"}.
	                          ^
14 errors


Deleting temporary directory: D:\eg\out\build\MinecraftSrc\src_javadoc_tmp

Error: failed to run javac compiler! exit code 1, check log
net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI$CompileFailureException: failed to run javac compiler! exit code 1, check log
	at net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI.runCompiler0(CompileLatestClientGUI.java:263)
	at net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI.runCompiler(CompileLatestClientGUI.java:138)
	at net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientFrame$2.run(CompileLatestClientFrame.java:325)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by vukle** [comment]
Strange, could you list the commands you ran and in order, I want to make sure if this error is on your side or not.

**Comment by OtterCodes102** [comment]
> Strange, could you list the commands you ran and in order, I want to make sure if this error is on your side or not.

i think he ran `"../jdk/bin/java" -cp BuildTools.jar net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI`

**Comment by vukle** [comment]
> > Strange, could you list the commands you ran and in order, I want to make sure if this error is on your side or not.
> 
> i think he ran `"../jdk/bin/java" -cp BuildTools.jar net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI`

Could be, but just need to make sure.

**Comment by NuraadGit** [comment]
he prob is

if so he should just run

chmod +x CompileLatestClient.sh

./CompileLatestClient.sh

**Comment by NuraadGit** [comment]
also isnt this the same guy who said he fixed it

"Fixed this by extracting the JDK's folders to the jdk folder in the project's root directory, cding into the buildtools directory and running "../jdk/bin/java" -cp BuildTools.jar net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI"

(terrible solution btw)

**Comment by NuraadGit** [comment]
just realized if your on windows you can try and compile with Java 17 cus that worked for me

**Comment by vukle** [comment]
closing since no activity

**Comment by NuraadGit** [comment]
trolled
